# Generated by Django 6.0.5 on 2026-05-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("sex", models.CharField(max_length=10)),
                ("cp", models.CharField(max_length=50)),
                ("trestbps", models.IntegerField()),
                ("chol", models.IntegerField()),
                ("fbs", models.CharField(max_length=5)),
                ("restecg", models.CharField(max_length=50)),
                ("thalch", models.IntegerField()),
                ("exang", models.CharField(max_length=5)),
                ("oldpeak", models.FloatField()),
                ("slope", models.CharField(max_length=20)),
                ("ca", models.IntegerField()),
                ("thal", models.CharField(max_length=50)),
                ("result", models.CharField(max_length=20)),
                ("probability", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
